# Generated by Django 5.2 on 2025-05-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('travel', 'Travelled Responsibly'), ('energy', 'Saved Energy'), ('food', 'Ate Sustainably'), ('waste', 'Managed Waste')], max_length=20)),
                ('amount', models.FloatField()),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
