# Generated by Django 5.2 on 2025-05-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_emissionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionlog',
            name='emitted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='emissionlog',
            name='saved',
            field=models.FloatField(default=0),
        ),
    ]
